# Generated by Django 3.2.16 on 2022-12-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='name',
            new_name='skillName',
        ),
    ]
