# Generated by Django 3.2.16 on 2022-12-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='disc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='img',
            new_name='featured_image',
        ),
    ]
