# Generated by Django 3.2.16 on 2022-12-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20221223_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='pojects/default.jpg', null=True, upload_to='uploaded-images/projects'),
        ),
    ]
