# Generated by Django 3.2.16 on 2023-01-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/project-default.jpg', null=True, upload_to='uploaded-images/projects'),
        ),
    ]
