# Generated by Django 3.2.16 on 2023-01-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_profile_image'),
        ('projects', '0010_auto_20230104_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
