# Generated by Django 3.2.16 on 2023-01-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'created_at']},
        ),
    ]
